version: '3.7'


services:
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:80
        environment: 
            - SECRET_KEY=ergff429)*pg$$1rk2u&)94x%otkc08o13m!v^$$wwb4m3f_8w(t
            - DEBUG=1
        volumes:
            - .:/code
        ports:
            - 80:80
        depends_on:
            - db
    db:
        image: postgres:11
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
    postgres_data: