version: '3.7'


services:
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:80
        volumes:
            - .:/code
        ports:
            - 80:80
        depends_on:
            - db
    db:
        image: postgres:11
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
    postgres_data: