version: '3.7'


services:
    web:
        build: .
        #command: python /code/manage.py runserver 0.0.0.0:80
        command: gunicorn bookstore_project.wsgi -b 0.0.0.0:80
        environment: 
            - ENVIRONMENT=development
            - SECRET_KEY=ergff429)*pg$$1rk2u&)94x%otkc08o13m!v^$$wwb4m3f_8w(t
            - DEBUG=1
            - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_51Gsw0IHrJJkrllBIdYMu3QIj08qo4q3T9YfIGZPlg58dfEMdUr9EbDgcXdwd29jll4RJOxplYymV5yOxhGzwawuI004OkJIYUT
            - STRIPE_TEST_SECRET_KEY=sk_test_51Gsw0IHrJJkrllBIMMcSSpO6IV1ziu6SkCUFHHI5W2AWupAc3jFaRnl0pABFdgPzppxg2ZZlgOeLVkZ9ceCOw2Q600z4NEcoCl
        volumes:
            - .:/code
        ports:
            - 80:80
        depends_on:
            - db
    db:
        image: postgres:11
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
    postgres_data: